module.exports.registerController = require("./auth/registerController");
module.exports.loginController = require("./auth/loginController");
module.exports.userController = require("./auth/userController");
module.exports.profileController = require("./auth/profileController");

module.exports.productController = require("./productController");
module.exports.categoryController = require("./categoryController");
module.exports.orderController = require("./orderController");
module.exports.adminOrderController = require("./admin/orderController");
module.exports.statusController = require("./admin/statusController");
module.exports.transactionController = require("./transactionController");
module.exports.dashboardController = require("./dashboardController");
module.exports.challengeController = require("./challengeController");
module.exports.notificationController = require("./notificationController");
module.exports.messageController = require("./messageController");

// export { default as registerController } from "./auth/registerController";
// export { default as loginController } from "./auth/loginController";
// export { default as userController } from "./auth/userController";
// export { default as profileController } from "./auth/profileController";
// export { default as productController } from "./productController";
// export { default as categoryController } from "./categoryController";
// export { default as orderController } from "./orderController";
// export { default as adminOrderController } from "./admin/orderController";
// export { default as statusController } from "./admin/statusController";
// export { default as transactionController } from "./transactionController";
// export { default as dashboardController } from "./dashboardController";
// export { default as challengeController } from "./challengeController";
// export { default as notificationController } from "./notificationController";
// export { default as messageController } from "./messageController";
