// export { default as User } from "./user";
// export { default as Product } from "./product";
// export { default as Category } from "./category";
// export { default as Order } from "./order";
// export { default as Transaction } from "./transaction";
// export { default as Challenge } from "./challenge";
// export { default as Notif_Tokens } from "./notif_tokens";
// export { default as Message } from "./message";
module.exports.User = require("./user");
module.exports.Product = require("./product");
module.exports.Category = require("./category");
module.exports.Transaction = require("./transaction");
module.exports.Order = require("./order");
module.exports.Challenge = require("./challenge");
module.exports.Notif_Tokens = require("./notif_Tokens");
module.exports.Message = require("./message");
