// export { default as User } from "./user";
// export { default as Product } from "./product";
// export { default as Category } from "./category";
// export { default as Order } from "./order";
// export { default as Transaction } from "./transaction";
// export { default as Challenge } from "./challenge";
// export { default as Notif_Tokens } from "./notif_tokens";
// export { default as Message } from "./message";
module.exports.User = require("./User");
module.exports.Product = require("./Product");
module.exports.Category = require("./Category");
module.exports.Transaction = require("./Transaction");
module.exports.Order = require("./Order");
module.exports.Challenge = require("./Challenge");
module.exports.Notif_Tokens = require("./Notif_Tokens");
module.exports.Message = require("./Message");
